"""create_permission_model

Revision ID: 019b4b167ea1
Revises: d7aacc5beb30
Create Date: 2022-08-30 09:11:08.855537

"""
from alembic import op
import sqlalchemy as sa
from src.db.settings.config import GUID


# revision identifiers, used by Alembic.
revision = '019b4b167ea1'
down_revision = 'd7aacc5beb30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('role_id', GUID(), nullable=True),
    sa.Column('route_id', GUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
