"""create_divergence_model

Revision ID: 0b8009009ddd
Revises: f168ea70d887
Create Date: 2022-10-26 09:23:17.086616

"""
from alembic import op
import sqlalchemy as sa
from src.db.settings.config import GUID

# revision identifiers, used by Alembic.
revision = '0b8009009ddd'
down_revision = 'f168ea70d887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divergences',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('email', sa.String(length=150), nullable=True),
        sa.Column('document', sa.String(length=11), nullable=False),
        sa.Column('role_id', GUID(), nullable=True),
        sa.Column('error', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'])
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divergences')
    # ### end Alembic commands ###
