"""add_new_fields_in_user

Revision ID: 1e0e01be23c3
Revises: 019b4b167ea1
Create Date: 2022-09-01 08:38:27.442401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0e01be23c3'
down_revision = '019b4b167ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_totvs', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['document'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_totvs')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
