"""create_roles

Revision ID: 260d9e0a1fe8
Revises: 
Create Date: 2022-08-08 10:16:16.665669

"""
from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from sqlalchemy import column, table, String
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '260d9e0a1fe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    role = table('roles',
                 column('id', postgresql.UUID(as_uuid=True)),
                 column('name', String),
                 )

    op.bulk_insert(role,
                   [
                       {'id': uuid4(), 'name': 'root'},
                       {'id': uuid4(), 'name': 'admin'},
                       {'id': uuid4(), 'name': 'professor'},
                       {'id': uuid4(), 'name': 'student'},
                   ]
                   )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
