"""create_role_model

Revision ID: c1ace52c8633
Revises: 
Create Date: 2022-08-11 16:36:05.766436

"""
from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from src.db.settings.config import GUID
from sqlalchemy import column, table, String


# revision identifiers, used by Alembic.
revision = 'c1ace52c8633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    role = table('roles',
                 column('id', GUID()),
                 column('name', String),
                 )

    op.bulk_insert(role,
                   [
                       {'id': uuid4(), 'name': 'root'},
                       {'id': uuid4(), 'name': 'admin'},
                       {'id': uuid4(), 'name': 'professor'},
                       {'id': uuid4(), 'name': 'student'},
                   ]
                   )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
