"""create_route_models_and_insert_routes

Revision ID: d7aacc5beb30
Revises: caa985fd62a9
Create Date: 2022-08-30 09:10:13.864536

"""
from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from src.db.settings.config import GUID

# revision identifiers, used by Alembic.
revision = 'd7aacc5beb30'
down_revision = 'caa985fd62a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
                    sa.Column('id', GUID(), nullable=True),
                    sa.Column('method', sa.String(length=30), nullable=False),
                    sa.Column('path', sa.String(length=100), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('now()'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('method', 'path')
                    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_id'), ['id'], unique=True)

    # ### end Alembic commands ###

    routes = sa.table('routes',
                      sa.column('id', GUID()),
                      sa.column('method', sa.String),
                      sa.column('path', sa.String)
                      )

    op.bulk_insert(routes, [
        {
            'id': uuid4(),
            'method': 'get',
            'path': '/role',
        },
        {
            'id': uuid4(),
            'method': 'get',
            'path': '/role/{id}',
        },
        {
            'id': uuid4(),
            'method': 'get',
            'path': '/user',
        },
        {
            'id': uuid4(),
            'method': 'get',
            'path': '/user/{id}',
        },
        {
            'id': uuid4(),
            'method': 'post',
            'path': '/user',
        },
        {
            'id': uuid4(),
            'method': 'patch',
            'path': '/user/{id}',
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_id'))

    op.drop_table('routes')
    # ### end Alembic commands ###
